CREATE DATABASE DESAFIO_ROMAN;

USE DESAFIO_ROMAN;

CREATE TABLE TIPOS_USUARIOS (
	ID INT IDENTITY PRIMARY KEY
	,NOME VARCHAR (255) NOT NULL UNIQUE	
);

CREATE TABLE EQUIPES (
	ID INT IDENTITY PRIMARY KEY
	,NOME VARCHAR (255) NOT NULL UNIQUE		
);

CREATE TABLE TEMAS (
	ID INT IDENTITY PRIMARY KEY
	,NOME VARCHAR (255) NOT NULL UNIQUE
	,SITUACAO CHAR (1)  --Pode ser um ENUM ou true/false ||| no princípio será null
);

CREATE TABLE USUARIOS ( --Pode ser tanto ADM's como Professores
	ID INT IDENTITY PRIMARY KEY
	,NOME VARCHAR (255) NOT NULL
	,EMAIL VARCHAR (250) NOT NULL UNIQUE
	,SENHA VARCHAR (250) NOT NULL
	,ID_EQUIPE INT FOREIGN KEY REFERENCES EQUIPES (ID)
	,ID_TIPO_USUARIO INT FOREIGN KEY REFERENCES TIPOS_USUARIOS (ID)	
);

CREATE TABLE PROJETOS (
	ID INT IDENTITY PRIMARY KEY
	,TITULO VARCHAR (255) NOT NULL UNIQUE	
	,DESCRICAO VARCHAR (255)
	,ID_USUARIO	INT FOREIGN KEY REFERENCES USUARIOS (ID)	
);

SELECT * FROM TIPOS_USUARIOS;
SELECT * FROM EQUIPES;
SELECT * FROM TEMAS;
SELECT * FROM USUARIOS;
SELECT * FROM PROJETOS;