CREATE DATABASE DESAFIO_ROMAN;

USE DESAFIO_ROMAN;

CREATE TABLE TIPOS_USUARIOS (
	ID INT IDENTITY PRIMARY KEY
	,NOME VARCHAR (255) NOT NULL UNIQUE	
);

CREATE TABLE EQUIPES (
	ID INT IDENTITY PRIMARY KEY
	,NOME VARCHAR (255) NOT NULL UNIQUE		
);

CREATE TABLE SITUACOES (
	ID INT IDENTITY PRIMARY KEY
	,NOME VARCHAR (255) NOT NULL UNIQUE		
);

CREATE TABLE TEMAS (
	ID INT IDENTITY PRIMARY KEY
	,NOME VARCHAR (255) NOT NULL UNIQUE
	,ID_SITUACAO INT FOREIGN KEY REFERENCES SITUACOES (ID) --Pode ser um true/false
);

CREATE TABLE USUARIOS ( --Pode ser tanto ADM's como Professores
	ID INT IDENTITY PRIMARY KEY
	,NOME VARCHAR (255) NOT NULL
	,EMAIL VARCHAR (250) NOT NULL UNIQUE
	,SENHA VARCHAR (250) NOT NULL
	,ID_TIPO_USUARIO INT FOREIGN KEY REFERENCES TIPOS_USUARIOS (ID)	
);

CREATE TABLE PROJETOS (
	ID INT IDENTITY PRIMARY KEY
	,TITULO VARCHAR (255) NOT NULL UNIQUE	
	,DESCRICAO VARCHAR (255)
	,ID_USUARIO	INT FOREIGN KEY REFERENCES USUARIOS (ID)	
);

CREATE TABLE USUARIOS_EQUIPES (
	ID_USUARIO INT FOREIGN KEY REFERENCES USUARIOS (ID)
	,ID_EQUIPE INT FOREIGN KEY REFERENCES EQUIPES (ID)
);

SELECT * FROM TIPOS_USUARIOS;
SELECT * FROM EQUIPES;
SELECT * FROM SITUACOES;
SELECT * FROM TEMAS;
SELECT * FROM USUARIOS;
SELECT * FROM PROJETOS;
SELECT * FROM USUARIOS_EQUIPES;

-----Sessão DELETE tables:

DROP TABLE USUARIOS_EQUIPES;
DROP TABLE PROJETOS;
DROP TABLE USUARIOS;
DROP TABLE TEMAS;
DROP TABLE SITUACOES;
DROP TABLE EQUIPES;
DROP TABLE TIPOS_USUARIOS;